### ISSUE TITLE
Expose ORCID on a user profile

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#191]
```gherkin
Given that a user has provided an ORCID
When I visit their profile page
Then I should see their ORCID with a link to their ORCID profile.
```

**Comment by cdeluca495** [comment]
Currently a user profile page in in CurateND does not show the ORCID id or any other id's(researcher id, scopus ID) UNLESS the user is in the "edit user profile" mode. In which case then, all three id fields are visible.  The user has to select the Orcid settings button to see the orcid information.
  A change should be made to make the ORCID(and perhaps other ID's) field visible on the users publicly available profile page.  The ID should link to their ORCID profile.
Attached are screenshots of the fields.
![2015-05-06_10-23-47](https://cloud.githubusercontent.com/assets/6973150/7495693/85175a92-f3dd-11e4-9365-27bc58e6c631.png)
![2015-05-06_10-24-03](https://cloud.githubusercontent.com/assets/6973150/7495695/87b863d6-f3dd-11e4-8e46-b75b648c897a.png)
![2015-05-06_10-24-22](https://cloud.githubusercontent.com/assets/6973150/7495704/8b577d42-f3dd-11e4-91a3-4b15034e3056.png)

**Comment by dbrower** [comment]
Will the label for the ORCID id be "Blog"?

**Comment by cdeluca495** [comment]
No, but good catch.  I wanted to see my orcid without having to go through the extra clicks so I just put the id into that field, in essence making it publicly visible.(in QA speak, that's a workaround ;) )
