### ISSUE TITLE
Change error handling from harbinger to errbit

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#204]
We are using [harbinger](https://github.com/ndlib/harbinger) to capture exceptions in CurateND. The rest of our applications have standardized around [errbit](https://github.com/errbit/errbit). Deprecate the old system in implement the new one.

**Comment by dbrower** [comment]
Is this issue still valid? Are we using errbit? If so I will make tickets for some other applications to send errors there (e.g. disadis, noids, bendo, batch-ingest)

**Comment by danhorst** [comment]
@dbrower we have several services using our self-hosted version of errbit @msuhovec has the details.

**Comment by jeremyf** [comment]
By switching to this, we can deprecate harbinger.
