### ISSUE TITLE
Publish “Content in Scope” policy

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#208]
The [CurateND Content in Scope policy](https://docs.google.com/document/d/1BX9F8PWttC4FL5ngfNK0s3d3RNJOPZSR45NJqD9kYqU/edit?usp=sharing) has been ratified. It needs to be made available on the website.

**Comment by rickjohnson** [comment]
I am thinking we will want to publish the full version plus a summary that references the full policy.  It would be something like:

CurateND accepts contributions from faculty, staff, students, researchers of the Notre Dame community.  CurateND welcomes the contribution of any scholarly works and supporting materials created by individuals affiliated with Notre Dame that can advance research for the greater scholarly community, regardless of digital format (text, data, image).  Read the full policy here for more detail (this would be linked)
