### ISSUE TITLE
Support “cool” URIs for collections in CurateND

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#214]
So called “cool” URIs, [as described by Sir. Tim](http://www.w3.org/Provider/Style/URI.html), are legegible and durable. Our requirements for a collection require the name to be immutable. This means that the name, or a derivative of the name, is an appropriate identifier in a “cool” URI:

Initially we will need a mapping, and a redirection, from the “cool” collection identifier to the appropriate facet value on the catalog page. The same URI will eventually resolve to a more elaborate presentation of the holdings of a collection.

```
https://curate.nd.edu/collections/colonial-currency
```
Should redirect to the appropriate parameters in the catalog view to display the contents of the “American Colonial Currency Collection”.

**Comment by dbrower** [comment]
This ticket is asking for some kind of purl service to be built into CurateND.

Would the mapping be stored in a database? Or as descriptive metadata on the collection? I'm leaning toward the latter. So then, how are conflicts where two collections as for the same path handled?
