### ISSUE TITLE
Adding an item to a collection from should maintain the current context

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#222]
Based on [Reid’s recommendations](https://docs.google.com/a/nd.edu/document/d/1lCbb_AUX6cFjya1cHcr355HKu95-7NfCgvQ1Jw-sofA/edit?usp=sharing):

Adding an item to a collection redirects the patron back to `/catalog`. 

- Making an addition to a collection from a search result listing should maintain the existing search results view and display an “added to collection” status notification.
- Making an addition to a collection from a record view should keep the patron on the same page and display an “added to collection” status notification.

---
The existing implementation of collections is being deprecated. The reason this task is still important is because profiles will continue to exist.

---
[Trello card](https://trello.com/c/kqVbGx0z)

**Comment by jeremyf** [comment]
Closed via https://github.com/ndlib/curate/commit/8f82ca7
