### ISSUE TITLE
Do not display thumbnails for witheld files

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#223]
If a patron does not have the privileges to view the “representative” file the thumbnail image cannot be displayed. The safest thing to do is to hide the thumbnail entirely if the patron cannot access the “representative” file.

See [DLTP-359](https://jira.library.nd.edu/browse/DLTP-359)

![screen_shot_2015-01-28_at_2 20 56_pm](https://cloud.githubusercontent.com/assets/2133/9917828/bb6e1960-5c91-11e5-93b1-9fcbf9088807.png)

---
[Trello card](https://trello.com/c/YDB8nMww)

**Comment by jeremyf** [comment]
The problem to address is to not have a broken image link.

**Comment by jeremyf** [comment]
Closed via https://github.com/ndlib/curate/commit/d10ab10
