### ISSUE TITLE
Improve the presentation of images in CurateND e.g. lightbox with larger-than-thumbnail

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#226]
We will need to decide what is an appropriate size for a presentation master. There are several options:

1. Generate (or require) a smaller image and display it in a lightbox
2. ~~Integrate with the image service/server that WSE built for DEC and add a zoomable viewer~~ WSE will not be maintaining an image server.
3. Use a third-party service like https://www.imgix.com/ to host and disseminate presentation derivatives

---
For the purposes of this issue use solution 1) and whatever lightbox library makes sense (colorbox, bootstrap, etc.).

---
[Trello card](https://trello.com/c/oKQCE5kd)

**Comment by jeremyf** [comment]
I'm uncertain about the specific implementation details. Does this mean when we click on a thumbnail from the search view that we render a Lightbox?

**Comment by danhorst** [comment]
@jeremyf this ticket only applies to the show view.
