### ISSUE TITLE
Need place to publish policies in CurateND

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/curate_nd#228]
Need a page to add CurateND's various policies: Content in Scope policy
Access rights and Use policy
Copyright

Some type of version control to document the changed in policies over time would be useful. Implemented with a json file perhaps?

URL:
`curate.nd.edu/policies`

Each policy should have a URI. Anchors are fine, individual pages may be better.

---
[Trello card](https://trello.com/c/yW8f7oGK/57-need-place-to-publish-policies-in-curatend)

**Comment by msuhovec** [comment]
Where can I find the 3 policies that are mentioned?

**Comment by msuhovec** [comment]
I'm deploying this on libvirt6
