### ISSUE TITLE
Strip control characters from metadata when indexing

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#268]
We received the solr error 'Illegal character ((CTRL-CHAR, code 12)) at [row,col {unknown-source}]: [1,4639]'

In this case the bad character was in the field "desc_metadata__abstract_tesim". It was with item und:5d86nz8249j.

@danhorst maybe just strip control characters when indexing? That would be easier than making sure all the stored data is (and will always be) kosher.

---
 [Trello card](https://trello.com/c/27WwtZs5)

**Comment by danhorst** [comment]
:+1: to filtering on index. Automated character encoding remediation for repository content is out of scope at this time.

**Comment by dbrower** [comment]
Not sure how localized this fix is. I hope it is not too big. If so, we can bump the milestone.
