### ISSUE TITLE
500 error in production

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#273]
I visit the following url and I get a 500 error: https://curate.nd.edu/concern/articles/4x51hh65r7d

going to the "show" page does not give an error. https://curate.nd.edu/show/4x51hh65r7d

This is from the production log file:
```
Started GET "/concern/articles/4x51hh65r7d" for 127.0.0.1 at 2015-11-03 12:46:42 -0500
Processing by CurationConcern::ArticlesController#show as HTML
  Parameters: {"id"=>"4x51hh65r7d"}
  Rendered curate/collections/_form_to_add_member.html.erb (9.2ms)
  Rendered application/_add_to_collection_gui.html.erb (12.4ms)
  Rendered curation_concern/articles/_attributes.html.erb (264.6ms)
  Rendered curation_concern/base/_doi.html.erb (5.3ms)
  Rendered curation_concern/base/show.html.erb within layouts/curate_nd/1_column (385.5ms)
BEGIN MESSAGE OBJECT ID=70252166274280
"exception.class_name" => ["URI::InvalidURIError"]
...
"exception.message" => ["bad URI(is not URI?): http://dx.doi.org/doi:PII S 0025-5718(2010)02399-3"]
"user.username" => ["dbrower"]
"request.path" => ["/concern/articles/4x51hh65r7d"]
"request.user_agent" => ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0"]
END MESSAGE OBJECT ID=70252166274280
Curate caught a registered error: URI::InvalidURIError
        bad URI(is not URI?): http://dx.doi.org/doi:PII S 0025-5718(2010)02399-3
        Backtrace:
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:176:in `split'
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/hydra-remote_identifier-0.6.7/lib/hydra/remote_identifier/remote_services/doi.rb:37:in `remote_uri_for'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/_doi.html.erb:5:in `_app_views_curation_concern_base__doi_html_erb__127568567289016659_70252165816640'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:278:in `render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:47:in `render_partial'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:27:in `render'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/show.html.erb:30:in `block in _app_views_curation_concern_base_show_html_erb__1145544355360852699_70252171314540'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in `capture'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/show.html.erb:28:in `_app_views_curation_concern_base_show_html_erb__1145544355360852699_70252171314540'
...
```

**Comment by cdeluca495** [comment]
It's my understanding that Dan may be working on a redirect rules so that
every thing redirects to the show page.

Sent from mobile. Please excuse my brevity.
(574)229-0456

On Nov 3, 2015, at 12:53 PM, Don Brower <notifications@github.com> wrote:

I visit the following url and I get a 500 error:
https://curate.nd.edu/concern/articles/4x51hh65r7d

going to the "show" page does not give an error.
https://curate.nd.edu/show/4x51hh65r7d

This is from the production log file:

Started GET "/concern/articles/4x51hh65r7d" for 127.0.0.1 at
2015-11-03 12:46:42 -0500
Processing by CurationConcern::ArticlesController#show as HTML
  Parameters: {"id"=>"4x51hh65r7d"}
  Rendered curate/collections/_form_to_add_member.html.erb (9.2ms)
  Rendered application/_add_to_collection_gui.html.erb (12.4ms)
  Rendered curation_concern/articles/_attributes.html.erb (264.6ms)
  Rendered curation_concern/base/_doi.html.erb (5.3ms)
  Rendered curation_concern/base/show.html.erb within
layouts/curate_nd/1_column (385.5ms)
BEGIN MESSAGE OBJECT ID=70252166274280
"exception.class_name" => ["URI::InvalidURIError"]
...
"exception.message" => ["bad URI(is not URI?):
http://dx.doi.org/doi:PII S 0025-5718(2010)02399-3"]
"user.username" => ["dbrower"]
"request.path" => ["/concern/articles/4x51hh65r7d"]
"request.user_agent" => ["Mozilla/5.0 (Macintosh; Intel Mac OS X
10.10; rv:43.0) Gecko/20100101 Firefox/43.0"]
END MESSAGE OBJECT ID=70252166274280
Curate caught a registered error: URI::InvalidURIError
        bad URI(is not URI?): http://dx.doi.org/doi:PII S 0025-5718(2010)02399-3
        Backtrace:
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:176:in `split'
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        /opt/ruby/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/hydra-remote_identifier-0.6.7/lib/hydra/remote_identifier/remote_services/doi.rb:37:in
`remote_uri_for'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/_doi.html.erb:5:in
`_app_views_curation_concern_base__doi_html_erb__127568567289016659_70252165816640'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in
`block in render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in
`block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in
`instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in
`render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:306:in
`render_partial'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:279:in
`block in render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in
`block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in
`block in instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in
`instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in
`instrument'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:278:in
`render'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:47:in
`render_partial'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:27:in
`render'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/show.html.erb:30:in
`block in _app_views_curation_concern_base_show_html_erb__1145544355360852699_70252171314540'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in
`block in capture'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:200:in
`with_output_buffer'
        /home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in
`capture'
        /home/app/curatend/releases/20151029164849/app/views/curation_concern/base/show.html.erb:28:in
`_app_views_curation_concern_base_show_html_erb__1145544355360852699_70252171314540'
...

—
Reply to this email directly or view it on GitHub
<https://github.com/ndlib/curate_nd/issues/273>.

**Comment by dbrower** [comment]
I did not get to this page via a redirect. This error happened yesterday to Parker. To get to it, search for "Regeneration Homotopies for Solving Systems of Polynomials", and then click on the first result (which should be an article of the same name).

@cdeluca495 do you mean that the `concern/articles` page is going away?

**Comment by rickjohnson** [comment]
This is only an isolated problem though, as it does not apply to every
resource, correct?

Thanks!
Rick

*Rick Johnson*
*Program Co-Director, Digital Initiatives and Scholarship*
*Head, Data Curation and Digital Library Solutions*
*Hesburgh Libraries*

*University of Notre Dame*
210 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1086
*e: *rick.johnson@nd.edu
http://orcid.org/0000-0002-1550-6325

<http://library.nd.edu/>

**Comment by dbrower** [comment]
The error is only with this resource as far as I know.

**Comment by dbrower** [comment]
I tried the link this morning and it still caused a 500 error. I had to be logged in for it to happen.

**Comment by dbrower** [comment]
Pinging this issue. I tried the link and I still get a 500 error.

The problem seems to be that the URL has a space in it? perhaps it is coming from the DOI?

**Comment by danhorst** [comment]
The error was caused by having a manually-entered DOI that did not parse correctly.

The original value for DOI:
```
doi:PII S 0025-5718(2010)02399-3
```
The correct value for the DOI attribute:
```
10.1090/S0025-5718-2010-02399-3
```
Which is presented as: http://dx.doi.org/10.1090/S0025-5718-2010-02399-3
