### ISSUE TITLE
Treat Document “subtypes” as a “Kind of Work”

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#355]
The “Kind of Work” facet for the `Document` work type should be indexed differently than other repository models. Instead of the class name, “Document”, it should be the value of the `type` attribute.

See [Project 15](https://docs.google.com/document/d/1V6MHVjpcJ4G_QGknqMTBndbuCAtagix1wRPHuxpYcfs/edit#heading=h.ky1p96owjt37) (limited to ND)

**Comment by dbrower** [comment]
Should I make a more detailed spec doc for this?

In my mind, it includes the following:

 * for documents, use the `dc:type` descMetadata as the document type for the show and edit pages.
 * Replace the active fedora model facet on the catalog page with a new facet on "Type". make sure the other content models index into this type (e.g. Dataset, ETD, Senior thesis, etc), and use the `dc:type` for documents.
 * I'm not sure how it will change the "create a new work" page. I think the document edit page should still offer the pull down to change `dc:type`.

How do these ideas sound. The main intention is to make the sub-type look like the actual type with as little work as possible. This is a stop-gap for "the real content model," whenever that happens. (Ruth and I have started discussing it already. And the external API will also define a content model.)

**Comment by banurekha** [comment]
I have created a sample work in libvirt8 to see how my change will look for documents with type. I will send the pid hipchat shortly for you to review. Let me know if that work for us.
