### ISSUE TITLE
Allow patrons to provide their email address when submitting a help request from an error page

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#364]
![curatend-364-add-contact-information-to-error-page](https://cloud.githubusercontent.com/assets/2133/14565264/398a5176-02f8-11e6-983c-29f2287ad609.png)

```gherkin
Given a patron is not logged in
When they encounter an error
Then they should be prompted to provide their contact information in their error report
```

```gherkin
Given a patron is logged in
When they encounter an error
Then their contact information should be pre-populated in their error report
```

When a patron encounters an error and is prompted to describe what they are doing the application does not capture _who they are_.

The view in question is `app/views/static_pages/error.html.erb`.

---
@JIRA DLTP-269
[JIRA ticket](https://jira.library.nd.edu/browse/DLTP-269)

**Comment by jeremyf** [comment]
I believe this will need to be added here:

https://github.com/ndlib/curate_nd/blob/bac4f910067df99bcfd13718d855e712eaf64b4b/app/views/help_requests/new.html.erb

It appears (according to the schema) that we are capturing the email for the help request.
