### ISSUE TITLE
Attribute formatting should never contain lists

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#376]
Attribute values are being parsed as Markdown. In most cases, including textual formatting and auto-linking, this is fine _but_ it is also parsing initials as lists. This is no good.

It is safe to assume that “single-line” attributes (including title) should _never_ contain lists. One way to accomplish this is to use a markdown parser that _does not support_ lists. This is [relatively straightforward using Redcarpet](https://github.com/vmg/redcarpet#block-level-calls).

![376-fix-attribute-formatting](https://cloud.githubusercontent.com/assets/2133/14614476/58fe68f2-056f-11e6-8fa4-64dcf82c7206.png)
[Example record](https://libvirt8.library.nd.edu/concern/documents/dev0012856h) (staging data is volatile)

- [x] Make a distinction between “inline” and “block” text rendering
- [x] Remove lists from “inline” text elements

**Comment by ruthtillman** [comment]
+1

**Comment by danhorst** [comment]
@ruthtillman this has been deployed to libvirt8. To my eye the example records display correctly.
