### ISSUE TITLE
Support Patent type

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#377]
See [Patent Project specifications](https://docs.google.com/document/d/1yJnTZ2dltY1KcmDJDWKX4B3YfEn_eorZfYnooEVko7E/edit)

# Modeling Patents
- [ ] Finalize what predicates we will be capturing, this is prework
  - [x] Method names on the object
  - [ ] Indexing strategies and predicates to use
- [x] Create a model analogue to CurateND's Article model
- [x] Create PatentsController analogue to ArticlesController
- [x] Create `CurationConcern::PatentActor`

# Creating Patents via the UI
This feature is not allowed

# Displaying and Discovering Patents
- [x] Create partial for display in search results (see `./app/views/curation_concern/senior_theses/_senior_thesis.html.erb` for reference)
- [x] Create show page and corresponding partials

# Editing Patents via the UI
- [x] Create forms for editing Patents

# Create Patent Review Groups in Prod and PPRD during deployment
- [ ] Create a group for Patent editors, as per the secrets `work_type_policy_rules.yml`
  - [x] Create a group of Patent Review group in curatend
  - [x] Assign members to that group (Don, Ruth, Parker Ladwig, Alexander Papson)
  - [x] Update the CurateND work_type_policy_rules.yml to be "open" for the Patent
  - [ ] Update CurateND work_type_policy_rules.yml to be "open" for the Patent Review Group (PID) in
     - [ ] Update secrets_pprd
     - [x] Update secrets_prod
     - [x] Update secrets_staging to be "Open" to all for Patent  

# Creating Patents via the Batch Process
Make sure to capture Patent Review Group Pid as a editor in right section when Ingesting

**Comment by ruthtillman** [comment]
Comment on back-end interface and general creation. These two fields are normally automatically created when a record is submitted. These fill out dateSubmitted and dateModified. Here, they have to be designated by users. Maybe @danhorst or @jeremyf has an example of the system doing it?

<img width="320" alt="screen shot 2016-05-06 at 2 14 39 pm" src="https://cloud.githubusercontent.com/assets/2687749/15082281/ed88732c-1394-11e6-8a1c-f2307c7a6400.png">

**Comment by banurekha** [comment]
Will take care of it.
