### ISSUE TITLE
Register a Service DN for Binding to LDAP

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#38]
Given that we may need to retrieve attributes from LDAP that are not
And that we may be hitting the LDAP server with several requests in a short period of time (i.e. updating all users with new attributes from LDAP)

Then we need a Service DN registered for curate.nd.edu to provide us with the rights to view additional non-public attributes.

We may need a similar Service DN registered for pre-production.

**Comment by dbrower** [comment]
I like the idea of tying in with the LDAP service. But the details on what we will do with the data are not  firm, and this issue seems to be speculative. Closing.
