### ISSUE TITLE
Streamline process for adding repository administrators

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#384]
- [x] Update RepoManager class to create records iff a username is present in `admin_usernames.yml`.
  - [x] Centralize knowledge about `admin_usernames.yml` into a utility class
  - [x] Update `db/seeds.rb`
  - [x] Update `app/constraints/curate_nd/admin_constraint.rb`
  - [x] Refactor `app/models/repo_manager.rb` and `app/controllers/repo_managers_controller.rb`
- [x] Add Parker to the list of repository administrators.

**Comment by danhorst** [comment]
@dbrower the need for a maunal database entry to grant privledges to a new repository administrator has been removed.

@jladwig will be able to act as a repository administrator the next time he logs into CurateND.
