### ISSUE TITLE
Enhance the show page view of the Image work type

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#396]
The show page for the image work type does not showcase the image content very well:
![image-work-current](https://cloud.githubusercontent.com/assets/2133/14966921/b3c65484-1082-11e6-8c64-e6d7300fe2de.png)

The representative image for of the image work type should much larger and presented in an image viewer like [OpenSeadragon](https://openseadragon.github.io/).
![image-work-enhanced-with-controls](https://cloud.githubusercontent.com/assets/2133/14966920/b3c559e4-1082-11e6-9316-3e7b4930ebda.png)

This feature was requested by @ruthtillman.

**Comment by ruthtillman** [comment]
Note on where this fits in prioritization: Project 10, Curate Project 2016.
