### ISSUE TITLE
Updating legacy Senior Thesis records causes a server error

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#412]
Making changes to a Senior Thesis can cause an uncaught application exception.

![curatend-412-senior-thesis-surprise](https://cloud.githubusercontent.com/assets/2133/15258130/d0f8b39c-1917-11e6-8df7-649c4f477172.png)

This appears to be a problem with date parsing during the translation to RDF.

---
**Example Records**

`und:12579s1621t`    https://curate.nd.edu/show/12579s1621t
`und:12579s16256`    https://curate.nd.edu/show/12579s16256
`und:8910js95f4g`    https://curate.nd.edu/show/8910js95f4g
`und:9g54xg94s6c`    https://curate.nd.edu/show/9g54xg94s6c
`und:cn69m326x9w`    https://curate.nd.edu/show/cn69m326x9w
`und:cn69m326z2s`    https://curate.nd.edu/show/cn69m326z2s
`und:cv43nv93h01`    https://curate.nd.edu/show/cv43nv93h01
`und:cz30pr76s1f`    https://curate.nd.edu/show/cz30pr76s1f
`und:sn009w03q9g`    https://curate.nd.edu/show/sn009w03q9g
`und:tb09j386q4m`    https://curate.nd.edu/show/tb09j386q4m
`und:w3763485q46`    https://curate.nd.edu/show/w3763485q46
`und:wp988g85d1z`    https://curate.nd.edu/show/wp988g85d1z
`und:zw12z317j2d`    https://curate.nd.edu/show/zw12z317j2d
`und:3r074t64k8t`    https://curate.nd.edu/show/3r074t64k8t
`und:9s161544m9s`    https://curate.nd.edu/show/9s161544m9s
`und:zw12z317j43`    https://curate.nd.edu/show/zw12z317j43

**Comment by laritakr** [comment]
Each of the above links which throw an error have "created" in the "descMetadata" datastream but there is no date. I didn't check all of the valid displays, but those I checked have the created date. 

I would guess that we are assuming that if the element is found, it contains a valid date, and are not looking for an invalid date.

Example: 
D, [2016-06-28T15:33:12.458706 #19233] DEBUG -- : Loaded datastream content und:12579s1621t/descMetadata (45.4ms)
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/dateSubmitted> "2013-03-18Z"^^<http://www.w3.org/2001/XMLSchema#date> .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/type> "Senior Thesis" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/title> "jhove 2 users guide" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/creator> "dbrower" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/description> "" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/created> "" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/creator#administrative_unit> "University of Notre Dame::Hesburgh Libraries::General" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/rights> "All rights reserved" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/identifier> "doi:10.7274/R0RN35SW" .
<info:fedora/und:12579s1621t> <http://purl.org/dc/terms/modified> "2016-05-13Z"^^<http://www.w3.org/2001/XMLSchema#date> .

**Comment by laritakr** [comment]
Another observation: 
https://curate.nd.edu/show/12579s1621t does not work in prod. 
https://curatepprd.library.nd.edu/show/12579s1621t works in pprd. 

When I looked for differences... in addition to the empty fields above no longer being there, the main thing I found was that descMetadata has both @datastream_content and @content in prod, but only @datastream_content in pprd.
