### ISSUE TITLE
Adjust Collection Behavior

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#413]
See [Collection Project specifications](https://docs.google.com/document/d/1ZjJz0tyEUsxpYo0oXsvb4lcoscFZ2qAsM2iJLdBvUyc/edit)

*NOTE: Work for this issue should be against the [project_17 branch](https://github.com/ndlib/curate_nd/tree/project_17) as there are several things to coordinate.*

# Updating Collection Model/Attributes
- [x] Update Collection descMetadata to account for Appendix A changes

# Creating Collections via the UI
~~- [ ] Though we don't create via the UI, update the existing collections forms to include the new attributes; We will revisit the UI as part of [Project 14](https://docs.google.com/document/d/1V6MHVjpcJ4G_QGknqMTBndbuCAtagix1wRPHuxpYcfs/edit#heading=h.fyjonjs1lnc9)~~

# Displaying and Discovering Collections
- [x] Update the Collection partial to include the new predicates

# Editing Collections via the UI
~~- [ ] Though we don't edit via the UI, update the existing collections forms to include the new attributes; We will revisit the UI as part of  [Project 14](https://docs.google.com/document/d/1V6MHVjpcJ4G_QGknqMTBndbuCAtagix1wRPHuxpYcfs/edit#heading=h.fyjonjs1lnc9)~~

**Comment by banurekha** [comment]
All the task in this issues are done and completed in Project_17 branch

**Comment by dbrower** [comment]
@jeremyf Is this ticket done?

**Comment by jeremyf** [comment]
I've amended the TODO items to remove the UI Edit/Create behavior
