### ISSUE TITLE
Change behavior of thumbnails for files on a Work show page

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#415]
At the bottom of a work there is a list of attached files. Each file has a thumbnail and an access rights badge along with buttons to "Download File" and "View Details". Currently clicking the thumbnail or access rights badge takes the user to the "View Details" page.

Most people don't care about the details page. It is annoying to go there. If someone really wants the details, there is a "View Details" button.

For these reasons, I want that behavior to change so that clicking the thumbnail or access badge will take the user to the "Download File" page. Also, make the file name be a link to "Download File".

![screen shot 2016-05-18 at 10 13 53 am](https://cloud.githubusercontent.com/assets/1843787/15362174/53029146-1ce2-11e6-84f5-d9ade63b6c93.png)

**Comment by ruthtillman** [comment]
I would be ok with this. I think it would also address a bit of a concern Alex had that our View Details page can be a bit confusing... so the fewer routes to get people there who don't _actually_ want to view the details, perhaps the better. Alex hadn't given any explicit suggestions re: it but I think this would mitigate some of that.
