### ISSUE TITLE
Patent dc:creator displays as "Creator" would prefer display as "Inventor"

### ISSUE THREAD

**Issue by ruthtillman** [ndlib/curate_nd#416]
Follow-up from subject specialist who would like to change the display label for dc:creator to "Inventor." @dbrower and I are ok with this change.

**Comment by ruthtillman** [comment]
@danhorst can we close this?

**Comment by danhorst** [comment]
Thanks for the heads up @ruthtillman. Most of the time issues are closed automatically because the `close-issue` script [adds a special comment to the commit message](https://github.com/ndlib/curate_nd/blob/master/script/close-issue#L108).
