### ISSUE TITLE
“Inventor From Local Institution” not being persisted for a Patent

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#419]
The “Inventor From Local Institution” field (`:creators_from_local_institution`) is not being persisted for the Patent work type.

If you enter a value on the create form and save the object the value is neither presented on the show view nor is it visible in the edit view.

**Comment by ruthtillman** [comment]
@dbrower tagging you in because I believe we may be ok with not showing it in the show view? I do not know. But it does need to be persisted.

**Comment by dbrower** [comment]
I think it is okay for not displaying it for now.

I would rather not have hidden metadata, though. Out of sight, out of mind.

**Comment by ruthtillman** [comment]
/nods. Basically display is not a crisis bug (persisting is important but thanks to the power of batch ingest not 100% critical at least because I can update from the sheet and now I have the tool to match pids), but I would agree we don't want to just forget we have it.
