### ISSUE TITLE
Ruby Model and Index Wrangling (Task D)

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#420]
See [Collection Project specifications](https://docs.google.com/document/d/1ZjJz0tyEUsxpYo0oXsvb4lcoscFZ2qAsM2iJLdBvUyc/edit)

*NOTE: Work for this issue should be against the [project_17 branch](https://github.com/ndlib/curate_nd/tree/project_17) as there are several things to coordinate.*

Upon exploration, this is dependent on #413 as it will involve moving collection behavior from `Hydra::Collections` into CurateND then modifying `RELS-EXT` behavior.

## Examples

Below is a proposed subgraph of collections and works. One thing to consider is that we are not imposing a collection depth restriction.

### Works and Collections
The arrow indicates an isMemberOf relationship (i.e. `b -> a` means `b isMemberOf a`)
![collections](https://cloud.githubusercontent.com/assets/2130/15898234/68080146-2d65-11e6-96d9-4a650236bf31.png "Collection Graph")

### Indexing

| node | parents | ancestors                                   | pathnames                     |
|------|---------|---------------------------------------------|-------------------------------|
| a    | []      | []                                          | [a]                           |
| b    | [a]     | [a]                                         | [a/b]                         |
| c    | [a, b]  | [a, a/b]                                    | [a/c, a/b/c]                  |
| d    | [b, c]  | [a, a/b, a/c, a/b/c]                        | [a/b/d, a/b/c/d, a/c/d]       |
| e    | [b, c]  | [a, a/b, a/c, a/b/c]                        | [a/b/e, a/b/c/e, a/c/e]       |
| f    | [e]     | [a, a/b, a/b/e, a/c, a/c/e, a/b/c, a/b/c/e] | [a/b/e/f, a/b/c/e/f, a/c/e/f] |

## Draft Acceptance Criteria

- [x] Work on the graph traversal as a separate object; There are lots of complicated interactions, so work on this in the abstract but allow for Fedora and SOLR to be injected as a dependency. (@jeremyf is working on this)
  - [x] The SOLR document should store the parents, ancestors, and pathnames (see above).
  - ~~The SOLR document should store the tree information regarding the index (i.e. A is member of B is member of C, means A would have is_transitive_member_of(A->B, A->B->C)); The tree is not necessary if we ever only add to collections, but becomes required if we remove items from collections.~~
- [x] Create the adapters the can be used to leverage the curate-indexer logic
- [x] Create a Job that can run asynchronously to reindex the relationships for a given document
  - [x] Account for the fact that the SOLR document may have changed in between the job's first retrieval of the document and the job attempting to write the SOLR document.
- ~~Write a single feature style spec that creates via commands the above set of data and verifies the values of the `#to_solr` for each of those documents.~~
  - ~~Define the SOLR document keys for each of the eight indexable items.~~
  - ~~Create a Job that takes a PID and walks up the graph, adjusting the direct/indirect work/collections isMemberOf/hasMembers~~
- ~~SOLR document for indexed item in a collection remains the same (i.e. the object's `collection_tesim` in the SOLR document should remain the same).~~
- ~~SOLR document for indexed collection remains the same (i.e. the collection's `has_collection_member_ssim` in the SOLR document should remain the same).~~
- ~~RELS-EXT for collection no longer includes reference to the contained works~~
- ~~RELS-EXT for works now includes reference collections~~
- [x] RELS-EXT for collection can include reference to other collections in which it is contained (via isMemberOfCollection)
- [x] Ensure that a Work page shows:
  - [x] What are my parent collections
  - ~~What are my ancestor collections~~
- [x] Ensure that a Collection page shows:
  - [x] What are my immediate child collections
  - [x] What are my immediate child works

## Considerations

- [x] When an object is added or removed from a collection, that object should be reindexed.
- ~~When a collection's membership is updated, that collection should be reindexed.~~
- [x] Collections can be part of other collections (See [Spec](https://docs.google.com/document/d/1ZjJz0tyEUsxpYo0oXsvb4lcoscFZ2qAsM2iJLdBvUyc/edit#heading=h.yah9igsy1mxt))
- [x] Beware of circular logic concerning collections (e.g. A is in B is in C is in A); Consider [Cycle Detection](https://en.wikipedia.org/wiki/Cycle_detection)

**Comment by ruthtillman** [comment]
This looks really good to me.

I would agree re: considering Cycle Detection. As Digital Collections Librarian, I should have some say in what gets added to what collection and be able to map and preclude any loops. _However_, I will not be Digital Collections Librarian as long as Curate is Curate, one hopes, and building with that kind of detection would be useful if it were either opened up (I'm assuming right now that Don would be the other person doing collections but that we'd both be talking about them) and if it were opened up in future or the next person were not entirely aware of the collections or any number of scenarios in which Don and I lose that control...better to detect now vs. break and then build a detector. If possible.

**Comment by dbrower** [comment]
re: cycle detection, there may also be a cycle from an error or mistake (human or computer).

**Comment by dbrower** [comment]
I find the label `indirect` is not quite precise enough. Maybe change it to just "hasMembers" or "AllMembers", or "AllParents" etc. Or TC[hasMembers], TC[isMemberOf] (TC = transitive closure)

**Comment by jeremyf** [comment]
@dbrower I'm going with transitive and removing "direct" as a label.

* is_member_of
* is_transitive_member_of
* has_members
* has_transitive_members

**Comment by jeremyf** [comment]
@dbrower I'm wondering the following is reasonable based on our previous conversation:

> The SOLR document should store the tree information regarding the index (i.e. A is member of B is member of C, means A would have is_transitive_member_of(A->B, A->B->C)); The tree is not necessary if we ever only add to collections, but becomes required if we remove items from collections.

**Comment by jeremyf** [comment]
I have been working on the reindexing strategy outside of CurateND so as to have fast specs and fast refactoring.

See https://github.com/ndlib/curate-indexer/

**Comment by jeremyf** [comment]
I've made amendments to the issues so I can put this in front of the team for review. Outstanding issues can be added to #439
