### ISSUE TITLE
Generate CSV of changed items

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#427]
Generate a CSV file of items that have changed or were modified in a given time period. The field list is defined in [Support Harvesting Content to SHARE - Project 24](https://docs.google.com/document/d/1kD4hegjUyFcB6sqFzWOY_6hpRn3rkMi29IoXXWkRkxk/edit#)
- [ ] Query SOLR for date range
- [ ] Generate CSV file and write to the file system
  - [ ] Note the column names should be the same as the SHARE name
  - [ ] The file name should be `curate-to-share-from-yyyymmdd-to-yyyymmdd.csv`
- [ ] Create an asynchronous job that:
  - [ ] Run with a `:from_date`, `:to_date`, and `:recipient_emails` parameters
  - [ ] Generates a CSV
  - [ ] Sends the CSV as an attachment to the provided email address

Assumption: The first request won't be via a web request; Instead we will perform the request by hand (as it could be a rather lengthy query).

**Comment by dbrower** [comment]
Is a background job needed? The make-csv-from-solr is pretty close to the level needed. And since this would be used in production only a few times, it is okay for it to require, say, me to make the file for Reid.

**Comment by dbrower** [comment]
I started the branch https://github.com/ndlib/curate_nd/tree/share-push-gateway and have added a few command line utilities to generate a CSV file for SHARE.
