### ISSUE TITLE
Push CSV to Share

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#428]
See for further details on task (https://docs.google.com/document/d/1kD4hegjUyFcB6sqFzWOY_6hpRn3rkMi29IoXXWkRkxk/edit#)

Related to #427

For each CSV row:
- [ ] Expand into JSON format that is expected by  [Share API](https://osf.io/api/v1/share/data/help/#!/SHARE/post_share_data)
- [ ] Post the JSON format to Share API
- [ ] Capture any non 2XX HTTP requests

For the job:
- [ ] If there are any non-2XX HTTP requests, Notify ERRBit of the exception

**Comment by dbrower** [comment]
Again I see this as a command line program. If you see it as needing to be more complicated (eg errbit), then ok..

Most of the difficulty here will be getting an endpoint set up with the COS people.

**Comment by dbrower** [comment]
I started the branch https://github.com/ndlib/curate_nd/tree/share-push-gateway and have added a few command line utilities to generate a CSV file for SHARE.

This is blocked on the SHARE people changing their API and not giving me access to the old one.
