### ISSUE TITLE
Sort departments on departmental landing page according to order in locabulary

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#447]
Added to JIRA - https://jira.library.nd.edu/browse/DLTP-512

The `/departments` page is built using the administrative unit facet values. Instead of listing the terms in alphabetical order these terms should be ordered according to their sequence in [locabulary](https://github.com/ndlib/locabulary). This will require enhancing or replacing the behavior in [`Blacklight::HierarchyHelper`](https://github.com/ndlib/blacklight-hierarchy/blob/master/app/helpers/blacklight/hierarchy_helper.rb).

- [x] Sort administrative units in “locabulary order“

Once the administrative units are sorted in “locabulary order“ `/departments` page should be limited to _only_ units in the University of Notre Dame. This should be accomplished with CSS scoped to the full page view. That way all the values can still be present on the facet modal view.

- [x] Hide all non-ND units on the `/departments` page

## Before
![curatend-447-sort-departmental-landing-page-before](https://cloud.githubusercontent.com/assets/2133/17176909/d80ad7be-53dc-11e6-91d3-e1fc64a1217e.png)

## After
![curatend-447-sort-departmental-landing-page-after](https://cloud.githubusercontent.com/assets/2133/17176913/de718e86-53dc-11e6-8417-75b15c9c4f03.png)

**Comment by ruthtillman** [comment]
And once sorting can be done, this page can be sure to only display things under University of Notre Dame, yes? Probably doesn't actually need University of Notre Dame header since page name "Departments and Units" does the trick.

**Comment by danhorst** [comment]
This might be possible. It would be easier to keep the content on the page
and in the facet selection window the same. That way I don't have to
conditionally filter out things from CRRA etc.

**Comment by ruthtillman** [comment]
I have a pretty strong feeling people would rather that be suppressed. Thinking logistically, if it's still coming from a place of top-level ol with nesting, Notre Dame now sorted to be on top, etc., would there be a way to use CSS to suppress display of everything but first child, aka ND? That's not a thing I really want to be saying and it may be fever-logic.

**Comment by danhorst** [comment]
That makes sense. If hiding content with CSS rather than excluding it from the markup entirely is acceptable it simplifies the implementation dramatically. `:first-child` FTW.

**Comment by danhorst** [comment]
Closed via PR 490
