### ISSUE TITLE
CommonObjects#show vs. CurationConcern/<Type>#show actions

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#471]
# User Stories

As a developer, I want to remove duplication of view logic, so that I can more easily maintain changes.
As a patron, I want to see a consistent presentation for an object, so that I can feel confident I am seeing all of the data.
As a patron, I want a single URL to view an object, so that its not as confusing.
# Details and Background

At present, there exists two methods for rendering an object. There is the "common objects" display page that resolves at `/show/:noid`. It is intended to be the persistent and permanent URL for those items. The second is the "specific" display page for a given work type that resolves at `/curation_concern/<type>/:noid`.

The work that was done related to #298 (Allow Curate ND to read items stored in Bendo) added the bendo handling to the "specific" display page, but not the "common objects" page. The end result is different behavior for displaying of files. This also manifests as different display methods.

I am proposing that instead of an alternate rendering of a custom template for the `/show/:noid` page we attempt to render the `show` template for the given CurationConcern.

To complete, verify that each of the following render the `/curation_concern/<type>/:noid` for the `/show/:noid` request.
- [ ] Articles
- [ ] Datasets
- [ ] Documents
- [ ] ETDs
- [ ] Finding Aids
- [ ] Generic Files
- [ ] Images
- [ ] Patents
- [ ] Senior Theses

**Comment by danhorst** [comment]
`/show/:noid` should be able to view _every_ type of object in the repository. This includes supporting `Collection` and `GenericWork` objects.

The collection view should include descriptive metadata about the collection without browsing or scoped searching of the collection contents.

`GenericWork` objects _shouldn’t_ be ending up in the production repository but the page should still be able to render successfully.

**Comment by ruthtillman** [comment]
So assuming I understand this correctly, I am perfectly ok with the "show" view essentially replicating the curation_concern/type view. I think having a consistent behavior for a work type across the repository is a good thing. 

Am ok with collection view in show just being descriptive information and curation_concern/type for it being the one where we get the actual items.

Also agree GenericWork should be able to render successfully vs. the weird error we get now.

**Comment by ruthtillman** [comment]
Related: https://docs.google.com/document/d/1MYVHKybdl_sob7xw1PlH2R1kaNPyJsJTszj7HphPDDY/edit# bringing it all under Project 33 as a combined effort to improve the display of objects with consistent behavior *and* displaying metadata fields that can be input.

When dealing with multiple values in a field, we're displaying them in multiple ways, depending on object type. This is the preferred form of display which should be standardized. https://curate.nd.edu/concern/documents/b8515m62w1j

**Comment by dbrower** [comment]
What about People, Groups, and other things with noids? (If they are in the repository, they need to be handled somehow, no?)
