### ISSUE TITLE
DOI should be stored in qualified DC term i.e., identifier#doi instead of identifier term.

### ISSUE THREAD

**Issue by rbalekai** [ndlib/curate_nd#48]
In Senior Thesis, the DOI is stored in identifier term. Instead it should be stored in Qualified DC term identifier#doi.

This will involve migration of the pre-existing senior thesis object.

**Comment by danhorst** [comment]
The DOI values are being stored as dc:identifier#doi for Articles, Datasets, Documents, ETDs, and Images.
