### ISSUE TITLE
GenericFile show view should not present an editor with a “Files” section

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#525]
```gherkin
Given that I can make changes to a GenericFile
When I view a “details” page for a GenericFile
Then I should NOT see a prompt to attach a file
```
Example record: https://libvirt9.library.nd.edu/show/dev00159168

### Show view without editing privileges:
![curatend-525-genericfile-file-list-view](https://cloud.githubusercontent.com/assets/2133/18275714/2f6a3c8a-7416-11e6-9e80-6e726cb1f93a.png)

### Existing show view with editing privileges:
![curatend-525-genericfile-file-list-edit-annotated](https://cloud.githubusercontent.com/assets/2133/18275722/3a79462a-7416-11e6-8e58-3377f18add47.png)

### Desired show view with editing privileges:
![curatend-525-genericfile-file-list-edit-desired](https://cloud.githubusercontent.com/assets/2133/18275742/4d05f784-7416-11e6-8428-6bb9d9d0abed.png)

**Comment by laritakr** [comment]
https://jira.library.nd.edu/browse/DLTP-587 completed.
